=== Esteban201483/appweb20a-Esteban-Joel/design/messages/mensaje.dtd
<!ENTITY % tesoros
    "agua|luna|estrella|cofre">

    <!ELEMENT mensaje (iniciarSesion|ingresoSalaEspera|partida| darCarta| asignarTurno|insertarFicha|actualizarTablero|
    moverAvatar| actualizarAvatar| otorgarTesoro| finalizarTurno| especificarGanador)*>

    <!ELEMENT iniciarSesion EMPTY>

    <!ELEMENT ingresoSalaEspera EMPTY>
    <!ATTLIST ingresoSalaEspera
        nombre NMTOKEN #REQUIRED
        avatar NMTOKEN #REQUIRED>

    <!ELEMENT partida (jugadores+,fichasTablero+)>
    <!ATTLIST partida
    host NMTOKEN #REQUIRED
    hostID NMTOKEN #REQUIRED
    avatarHost NMTOKEN #REQUIRED
    timer NMTOKEN #REQUIRED
    numeroJugadores NMTOKEN #REQUIRED
    filas NMTOKEN #REQUIRED
    columnas NMTOKEN #REQUIRED>

    <!ELEMENT jugadores (jugador+)>
    <!ELEMENT jugador EMPTY>
    <!ATTLIST jugador
        nombre NMTOKEN #REQUIRED
        avatar NMTOKEN #REQUIRED
        jugadorID NMTOKEN #REQUIRED>
    
    <!ELEMENT fichasTablero (ficha+)>
    <!ELEMENT ficha EMPTY>
    <!ATTLIST ficha
        tipo NMTOKEN #REQUIRED
        tesoro NMTOKEN #IMPLIED
        jugador NMTOKEN #IMPLIED>

    <!ELEMENT darCarta EMPTY>
    <!ATTLIST darCarta 
        carta (agua|luna|estrella|cofre) #REQUIRED>

    <!ELEMENT asignarTurno EMPTY>
    <!ATTLIST asignarTurno
        jugador NMTOKEN #REQUIRED>

    <!ELEMENT insertarFicha EMPTY>
    <!ATTLIST insertarFicha
        fila NMTOKEN #REQUIRED
        columna NMTOKEN #REQUIRED
        ficha NMTOKEN #REQUIRED>

    <!ELEMENT actualizarTablero EMPTY>
    <!ATTLIST actualizarTablero
        fila NMTOKEN #REQUIRED
        columna NMTOKEN #REQUIRED
        ficha NMTOKEN #REQUIRED>

    <!ELEMENT moverAvatar EMPTY>
    <!ATTLIST moverAvatar
        fila NMTOKEN #REQUIRED
        columna NMTOKEN #REQUIRED>

    <!ELEMENT actualizarAvatar EMPTY>
    <!ATTLIST actualizarAvatar
        fila NMTOKEN #REQUIRED
        columna NMTOKEN #REQUIRED>

    <!ELEMENT finalizarTurno EMPTY>

    <!ELEMENT otorgarTesoro EMPTY>
    <!ATTLIST otorgarTesoro 
        tesoroEncontrado (agua|luna|estrella|cofre) #REQUIRED>

    <!ELEMENT especificarGanador EMPTY>

=== Esteban201483/appweb20a-Esteban-Joel/design/messages/messages1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE mensaje SYSTEM "mensaje.dtd">

<mensaje>

    <!-- from server to all -->
    <iniciarSesion />

    <!-- from server to all -->
    <ingresoSalaEspera nombre="Joel" avatar="avatar_verde" />

    <!-- from server to all -->
    <ingresoSalaEspera nombre="Esteban" avatar="avatar_morado" />

    <!-- from server to all -->
    <partida host="Joel" hostID="1" avatarHost="avatar_verde" timer="120" numeroJugadores="2" filas="5" columnas="5">
        <jugadores>
            <jugador nombre="Esteban" jugadorID="2" avatar="avatar_morado"  />
        </jugadores>
        <fichasTablero>
            <ficha tipo="6" jugador="1"/>
            <ficha tipo="7" />
            <ficha tipo="0" />
            <ficha tipo="5" />
            <ficha tipo="7" />
            <ficha tipo="0" />
            <ficha tipo="10" />
            <ficha tipo="5" tesoro="Estrella" />
            <ficha tipo="3" />
            <ficha tipo="3" />
            <ficha tipo="9" />
            <ficha tipo="7" tesoro="Luna" />
            <ficha tipo="5" />
            <ficha tipo="5" tesoro="Cofre" />
            <ficha tipo="3" />
            <ficha tipo="6" />
            <ficha tipo="0" />
            <ficha tipo="5" tesoro="Agua" />
            <ficha tipo="0" />
            <ficha tipo="3" />
            <ficha tipo="7" />
            <ficha tipo="10" />
            <ficha tipo="6" />
            <ficha tipo="10" />
            <ficha tipo="9" />
            <ficha tipo="6" />
        </fichasTablero>
    </partida>
    <!-- from server to Joel -->
    <darCarta carta="estrella" />

    <!-- from server to Esteban -->
    <darCarta carta="agua" />

    <!-- from server to all -->
    <asignarTurno jugador="1" />

    <!-- from Joel to server -->
    <insertarFicha fila="4" columna="1" ficha="6" />

    <!-- from server to all -->
    <actualizarTablero fila="4" columna="1" ficha="6" />

    <!-- from Joel to server -->
    <moverAvatar fila="0" columna="1" />

    <!-- from server to all -->
    <actualizarAvatar fila="0" columna="1" />

    <!-- from Joel to server -->
    <finalizarTurno />

    <!-- from server to all -->
    <asignarTurno jugador="2" />

    <!-- from Esteban to server -->
    <insertarFicha fila="4" columna="3" ficha="7" />

    <!-- from server to all -->
    <actualizarTablero fila="4" columna="3" ficha="7" />

    <!-- from Esteban to server -->
    <moverAvatar fila="3" columna="2" />

    <!-- from server to all -->
    <actualizarAvatar fila="3" columna="2" />

    <!-- from Esteban to server -->
    <finalizarTurno />

    <!-- from Server to all -->
    <otorgarTesoro tesoroEncontrado="agua" />

    <!-- from Server to Esteban -->
    <darCarta carta="cofre" />


    <!-- from Server to all -->
    <asignarTurno jugador="1" />

    <!-- from Joel to server -->
    <insertarFicha fila="0" columna="1" ficha="9" />

    <!-- from server to all -->
    <actualizarTablero fila="0" columna="1" ficha="9" />

    <!-- from Joel to server -->
    <moverAvatar fila="0" columna="1" />

    <!-- from server to all -->
    <actualizarAvatar fila="0" columna="1" />

    <!-- from Joel to server -->
    <finalizarTurno />


    <!-- from server to all -->
    <asignarTurno jugador="2" />

    <!-- from Esteban to server -->
    <insertarFicha fila="0" columna="1" ficha="3" />

    <!-- from server to all -->
    <actualizarTablero fila="0" columna="1" ficha="3" />

    <!-- from Esteban to server -->
    <moverAvatar fila="1" columna="2" />

    <!-- from server to all -->
    <actualizarAvatar fila="1" columna="2" />

    <!-- from Esteban to server -->
    <finalizarTurno />

    <!-- from Server to all -->
    <otorgarTesoro tesoroEncontrado="cofre" />

    <especificarGanador />

</mensaje>
